/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    DepositModal: typeof import('./src/components/DepositModal.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}

// For TSX support
declare global {
  const CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
  const CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
  const CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
  const DepositModal: typeof import('./src/components/DepositModal.vue')['default']
  const ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const LoginModal: typeof import('./src/components/LoginModal.vue')['default']
  const MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
  const UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
  const VueApexCharts: typeof import('vue3-apexcharts')['default']
}